networks:
  pa-dev:
    driver: bridge

services:
  pa.api:
    container_name: pa.api
    image: pa.api
    build:
      context: .
      dockerfile: ProductionAnalysis.Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "pa.db"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - pa.db
  
  pa.db:
    container_name: pa.db
    image: postgres:18.0-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: