// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductionAnalysis.Data.Context;

#nullable disable

namespace ProductionAnalysis.Data.Migrations
{
    [DbContext(typeof(PaDbContext))]
    [Migration("20260118204446_renameColumnInForms")]
    partial class renameColumnInForms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.AuxiliaryOperationDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auxiliary_operations");

                    b.ToTable("auxiliary_operations", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.DepartmentDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_departments_enterprise_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.DowntimeReasonGroupDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_downtime_reason_groups");

                    b.ToTable("downtime_reason_groups", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.EmployeeDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("middle_name");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_employees_department_id");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_employees_position_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_employees_user_id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.EnterpriseDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_enterprises");

                    b.ToTable("enterprises", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.IndicatorDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Formula")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("formula");

                    b.Property<bool>("HasSummation")
                        .HasColumnType("boolean")
                        .HasColumnName("has_summation");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("input_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ValueSelector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value_selector");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_indicators");

                    b.ToTable("indicators", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.OperationDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasedOnType")
                        .HasColumnType("integer")
                        .HasColumnName("based_on_type");

                    b.Property<int?>("BasedOperationId")
                        .HasColumnType("integer")
                        .HasColumnName("based_operation_id");

                    b.Property<int?>("BasedProductId")
                        .HasColumnType("integer")
                        .HasColumnName("based_product_id");

                    b.Property<int?>("DurationInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("BasedOperationId")
                        .HasDatabaseName("ix_operations_based_operation_id");

                    b.HasIndex("BasedProductId")
                        .HasDatabaseName("ix_operations_based_product_id");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.PositionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.ProductDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("integer")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("TactTimeInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tact_time_in_seconds");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_products_enterprise_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.ShiftDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.ShiftScheduleDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuxiliaryOperationId")
                        .HasColumnType("integer")
                        .HasColumnName("auxiliary_operation_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shift_schedules");

                    b.HasIndex("AuxiliaryOperationId")
                        .HasDatabaseName("ix_shift_schedules_auxiliary_operation_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_shift_schedules_shift_id");

                    b.ToTable("shift_schedules", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.TemplateDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PaTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("pa_type_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.TemplateIndicatorDbo", b =>
                {
                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int?>("TemplateDboId")
                        .HasColumnType("integer")
                        .HasColumnName("template_dbo_id");

                    b.HasKey("TemplateId", "IndicatorId")
                        .HasName("pk_templates_indicators");

                    b.HasIndex("IndicatorId")
                        .HasDatabaseName("ix_templates_indicators_indicator_id");

                    b.HasIndex("TemplateDboId")
                        .HasDatabaseName("ix_templates_indicators_template_dbo_id");

                    b.ToTable("templates_indicators", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("FormDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("form_date");

                    b.Property<Guid>("LastEditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_editor_id");

                    b.Property<int>("PaTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("pa_type_id");

                    b.Property<int>("ShiftId")
                        .HasColumnType("integer")
                        .HasColumnName("shift_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TemplateSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("template_snapshot");

                    b.Property<string>("TotalValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("total_values");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_forms_assignee_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_forms_creator_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_forms_department_id");

                    b.HasIndex("LastEditorId")
                        .HasDatabaseName("ix_forms_last_editor_id");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_forms_shift_id");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormRowDbo", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<short>("Order")
                        .HasColumnType("smallint")
                        .HasColumnName("order");

                    b.Property<int?>("AuxiliaryOperationId")
                        .HasColumnType("integer")
                        .HasColumnName("auxiliary_operation_id");

                    b.Property<int?>("GroupKey")
                        .HasColumnType("integer")
                        .HasColumnName("group_key");

                    b.Property<bool>("IsAuxiliaryOperation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_auxiliary_operation");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.HasKey("FormId", "Order")
                        .HasName("pk_form_rows");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_rows_form_id");

                    b.ToTable("form_rows", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormRowValueDbo", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<short>("FormRowOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("form_row_order");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicator_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("FormId", "FormRowOrder", "IndicatorId")
                        .HasName("pk_form_row_values");

                    b.HasIndex("IndicatorId")
                        .HasDatabaseName("ix_form_row_values_indicator_id");

                    b.HasIndex("FormId", "FormRowOrder")
                        .HasDatabaseName("ix_form_row_values_form_id_form_row_order");

                    b.ToTable("form_row_values", (string)null);
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.UserDbo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("middle_name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.DepartmentDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.EnterpriseDbo", null)
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_enterprises_enterprise_id");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.EmployeeDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.DepartmentDbo", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.PositionDbo", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employees_positions_position_id");

                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_employees_users_user_id");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.OperationDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.OperationDbo", null)
                        .WithMany()
                        .HasForeignKey("BasedOperationId")
                        .HasConstraintName("fk_operations_operations_based_operation_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.ProductDbo", null)
                        .WithMany()
                        .HasForeignKey("BasedProductId")
                        .HasConstraintName("fk_operations_products_based_product_id");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.ProductDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.EnterpriseDbo", null)
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_enterprises_enterprise_id");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.ShiftScheduleDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.AuxiliaryOperationDbo", "AuxiliaryOperation")
                        .WithMany()
                        .HasForeignKey("AuxiliaryOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_schedules_auxiliary_operations_auxiliary_operation_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.ShiftDbo", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_schedules_shifts_shift_id");

                    b.Navigation("AuxiliaryOperation");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.TemplateIndicatorDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.IndicatorDbo", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_templates_indicators_indicators_indicator_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.TemplateDbo", null)
                        .WithMany("TemplateIndicators")
                        .HasForeignKey("TemplateDboId")
                        .HasConstraintName("fk_templates_indicators_templates_template_dbo_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.TemplateDbo", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_templates_indicators_templates_template_id");

                    b.Navigation("Indicator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.EmployeeDbo", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forms_employees_assignee_id");

                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forms_users_creator_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.DepartmentDbo", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forms_departments_department_id");

                    b.HasOne("ProductionAnalysis.Data.Models.UserDbo", null)
                        .WithMany()
                        .HasForeignKey("LastEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forms_users_last_editor_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.ShiftDbo", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_forms_shifts_shift_id");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormRowDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Forms.FormDbo", "Form")
                        .WithMany("FormRows")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_rows_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormRowValueDbo", b =>
                {
                    b.HasOne("ProductionAnalysis.Data.Models.Dictionaries.IndicatorDbo", "Indicator")
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_form_row_values_indicators_indicator_id");

                    b.HasOne("ProductionAnalysis.Data.Models.Forms.FormRowDbo", "FormRow")
                        .WithMany("Values")
                        .HasForeignKey("FormId", "FormRowOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_row_values_form_rows_form_id_form_row_order");

                    b.Navigation("FormRow");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Dictionaries.TemplateDbo", b =>
                {
                    b.Navigation("TemplateIndicators");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormDbo", b =>
                {
                    b.Navigation("FormRows");
                });

            modelBuilder.Entity("ProductionAnalysis.Data.Models.Forms.FormRowDbo", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
